When uploading a new image, the last image used by the user is deleted from the container.
Alejandro-HUB/Muszilla pull request #3
Opened 2022-05-22 21:23 UTC by Oozaru71

I am not experiencing the "Image upload button when clicked shows two dialogs." issue you mentioned.

2022-05-22 21:33 UTC, Alejandro-HUB requested changes

2022-05-22 21:33 UTC, Alejandro-HUB commented on Controllers/ImagesController.cs
> +            BlobContainerClient containerC = new BlobContainerClient("DefaultEndpointsProtocol=https;AccountName=devstorageale;AccountKey=l2Fo6os7kVCIZZ992p5NavyHar3SjUMQStiV1Ac89NLSJOOTPu6RAlmf9QoRG
Let's try not to use credentials in the code. Try to add this to app settings or to resources. It is bad practice to have it so easily accesible.

2022-05-23 14:27 UTC, Oozaru71 commented
I have fixed the credential issue as well as the upload screens issue.

2022-05-23 14:28 UTC, Oozaru71 commented
#3 completed

2022-05-24 04:12 UTC, Alejandro-HUB approved these changes

2022-05-24 04:12 UTC, Alejandro-HUB commented
Approved, great job Michael. I will get started on making our following tasks.

2022-05-24 04:13 UTC, merged