Adjust login and sign up
Alejandro-HUB/Muszilla pull request #7
Opened 2022-06-05 22:48 UTC by Oozaru71

Made quite a few changes but i left a summary of the most noticeable ones but now everything should be as expected,

2022-06-06 01:50 UTC, Alejandro-HUB requested changes

2022-06-06 01:50 UTC, Alejandro-HUB commented on Views/Home/Index.cshtml
> +          <img src="/css2/images/logo.png" alt="." class="hide">
I mentioned them on the video but I’ll write it here too.

1) The logo on the top left
2) Logout button
3) Positioning of the music bar
4) Positioning of the picture on the left panel

2022-06-06 18:35 UTC, Alejandro-HUB requested changes

2022-06-06 18:35 UTC, Alejandro-HUB commented on Views/Home/Index.cshtml
> +                <a href="modal.lockme.html" data-toggle="ajaxModal" >Logout</a>
To add the logic for the logout button you need to go inside the ajax modal that gets triggered once you click your name. You will find the logout button inside modal.lockme.html.

Also, you do not need to create another pull request when you push your changes the pull request gets automatically updated. Which is why I am denying your other pull request.

Finally, the logo is a css issue all you need to do is look at which is one has css that messes up the other. If you think its the user picture then look into the user picture's css and make it smaller or play around with it.

2022-06-14 20:08 UTC, Oozaru71 commented
I have fixed both problems, log out and avatar pic size.

2022-06-15 04:18 UTC, Alejandro-HUB approved these changes
Great job, it's looking good. I will assign a new task to you tomorrow 👍

2022-06-15 04:18 UTC, merged